namespace Tempo.Blazor.Components.Wireframe;

/// <summary>Built-in Tempo UI role vocabulary used as the global baseline.</summary>
public sealed class BuiltInUiRoleVocabularySource : IUiRoleVocabularySource
{
    private static readonly IReadOnlyList<UiRoleDefinition> Roles =
    [
        R("button", "Button", "Triggers a primary or secondary user action.", "action button", "tlacitko", "TmButton"),
        R("split-button", "Split button", "Combines a default action with a menu of related actions.", "dropdown button", "rozbalovaci tlacitko", "TmSplitButton"),
        R("copy-button", "Copy button", "Copies a value to the clipboard.", "clipboard button", "kopirovaci tlacitko", "TmCopyButton"),
        R("floating-action-button", "Floating action button", "Prominent floating action control.", "fab", "plovouci tlacitko", "TmFloatingActionButton"),
        R("avatar", "Avatar", "Represents a person or entity visually.", "user picture", "profilovy obrazek", "TmAvatar"),
        R("avatar-group", "Avatar group", "Displays multiple avatars as a compact group.", "people group", "skupina avataru", "TmAvatarGroup"),
        R("icon", "Icon", "Small symbolic visual used to identify an action or object.", "symbol", "ikona", "TmIcon"),
        R("heading", "Heading", "Section title or page heading text.", "title", "nadpis", "TmHeading"),
        R("link", "Link", "Navigates to another page, document, or target.", "anchor", "odkaz", "TmLink"),
        R("text", "Text", "Static or formatted text content.", "label text", "textovy obsah", "TmText"),
        R("text-input", "Text input", "Accepts a short free-text value.", "text field", "input", "vstupni pole", "TmTextInput", "TmTextField"),
        R("text-area", "Text area", "Accepts multi-line free-text content.", "textarea", "vice radku", "TmTextArea"),
        R("number-input", "Number input", "Accepts numeric values.", "numeric input", "cislo", "TmNumberInput"),
        R("search-input", "Search input", "Accepts a query for filtering or finding content.", "search box", "search field", "vyhledavani", "TmSearchInput", "TmSearchBox"),
        R("currency-input", "Currency input", "Accepts monetary amounts.", "money input", "mena", "TmCurrencyInput"),
        R("decimal-input", "Decimal input", "Accepts decimal values with culture-aware formatting, optionally as a percentage.", "decimal field", "percent input", "desetinne cislo", "procenta", "TmDecimalInput"),
        R("checkbox", "Checkbox", "Captures an independent boolean choice.", "check box", "zaskrtavatko", "TmCheckbox"),
        R("radio", "Radio", "Captures one choice inside an exclusive option group.", "radio button", "prepinac volby", "TmRadio"),
        R("radio-group", "Radio group", "Groups exclusive radio choices.", "option group", "skupina voleb", "TmRadioGroup"),
        R("toggle", "Toggle", "Switches a setting between on and off.", "switch", "prepinac", "TmToggle", "TmSwitch"),
        R("segmented-control", "Segmented control", "Switches between a small set of mutually exclusive modes.", "segments", "prepinac segmentu", "TmSegmentedControl"),
        R("select", "Select", "Chooses one value from a list.", "select box", "vyber", "TmSelect"),
        R("multi-select", "Multi-select", "Chooses multiple values from a list.", "multiple select", "vice vyberu", "TmMultiSelect"),
        R("cascading-select", "Cascading select", "Chooses values through dependent hierarchical lists.", "dependent select", "kaskadovy vyber", "TmCascadingSelect"),
        R("dropdown", "Dropdown", "Opens a menu or list of options.", "drop down", "rozbalovaci seznam", "TmDropdown", "TmDropdownItem"),
        R("entity-picker", "Entity picker", "Finds and selects a domain entity.", "record picker", "vyber entity", "TmEntityPicker", "TmUserPicker"),
        R("expression-editor", "Expression editor", "Builds or edits a formula-like expression.", "rule editor", "editor vyrazu", "TmExpressionEditor"),
        R("password-strength", "Password strength", "Shows password quality feedback.", "password meter", "sila hesla", "TmPasswordStrengthIndicator"),
        R("slider", "Slider", "Selects a numeric value on a continuous scale.", "range input", "posuvnik", "TmSlider"),
        R("range-slider", "Range slider", "Selects a numeric interval on a continuous scale.", "interval slider", "rozsahovy posuvnik", "TmRangeSlider"),
        R("rating", "Rating", "Captures or displays a score.", "stars", "hodnoceni", "TmRating"),
        R("masked-input", "Masked input", "Accepts text using a fixed mask or pattern.", "masked textbox", "maskovane pole", "TmMaskedTextBox"),
        R("combo-box", "Combo box", "Combines typed search with list selection.", "combobox", "kombinovany vyber", "TmMultiColumnComboBox"),
        R("signature-pad", "Signature pad", "Captures a drawn signature.", "signature capture", "podpis", "TmSignature", "TmSignatureCapture"),
        R("otp-input", "OTP input", "Collects a one-time password or verification code.", "one-time password", "verification code", "jednorazovy kod", "TmOtpInput"),
        R("tag-picker", "Tag picker", "Chooses one or more tags.", "tag selector", "vyber stitku", "TmTagPicker"),
        R("date-picker", "Date picker", "Chooses a calendar date.", "calendar picker", "vyber data", "TmDatePicker"),
        R("datetime-picker", "Date and time picker", "Chooses a date with a time.", "date time picker", "vyber data a casu", "TmDateTimePicker"),
        R("time-picker", "Time picker", "Chooses a time of day.", "time selector", "vyber casu", "TmTimePicker", "TmTimeInput"),
        R("date-range-picker", "Date range picker", "Chooses a date interval.", "date interval", "rozsah dat", "TmDateRangePicker", "TmTimeRangePicker", "TmDateTimeRangePicker"),
        R("calendar-view", "Calendar view", "Displays dates or events in a calendar grid.", "calendar", "kalendar", "TmCalendarView", "TmCalendarGrid"),
        R("recurrence-editor", "Recurrence editor", "Configures repeated schedule rules.", "repeat rules", "opakovani", "TmRecurrenceEditor"),
        R("badge", "Badge", "Displays a compact status, count, or category.", "status badge", "stitek", "TmBadge"),
        R("chip", "Chip", "Displays a compact token or selected item.", "pill", "stitkovy prvek", "TmChip", "TmChipGroup"),
        R("card", "Card", "Groups related content and actions.", "panel", "karta", "TmCard"),
        R("stat-card", "Stat card", "Highlights a key metric.", "metric card", "metricka karta", "TmStatCard"),
        R("accordion", "Accordion", "Shows collapsible content sections.", "collapsible section", "rozbalovaci sekce", "TmAccordion", "TmAccordionItem"),
        R("empty-state", "Empty state", "Explains that no data or content is available.", "blank state", "prazdny stav", "TmEmptyState"),
        R("diff-view", "Diff view", "Shows differences between two values or versions.", "change diff", "porovnani zmen", "TmChangeDiff"),
        R("kanban-board", "Kanban board", "Shows work items in draggable columns.", "kanban", "kanban tabule", "TmKanbanBoard"),
        R("list-view", "List view", "Displays records as a list or multiple saved views.", "multi view list", "seznam", "TmMultiViewList"),
        R("data-table", "Data table", "Displays tabular records with data operations.", "data grid", "grid", "tabulka dat", "TmDataTable", "TmDataGrid"),
        R("pagination", "Pagination", "Moves through pages of data.", "pager", "strankovani", "TmPagination"),
        R("bulk-action-bar", "Bulk action bar", "Shows actions for selected items.", "bulk actions", "hromadne akce", "TmBulkActionBar"),
        R("column-filter", "Column filter", "Filters data by a table column.", "column search", "filtr sloupce", "TmColumnFilter"),
        R("column-picker", "Column picker", "Controls visible table columns.", "column chooser", "vyber sloupcu", "TmColumnPicker"),
        R("view-manager", "View manager", "Stores and switches saved data views.", "saved views", "sprava pohledu", "TmViewManager"),
        R("alert", "Alert", "Displays an inline message with severity.", "notice", "upozorneni", "TmAlert"),
        R("modal", "Modal", "Shows blocking overlay content.", "modal window", "modalni okno", "TmModal"),
        R("dialog", "Dialog", "Asks for confirmation or focused input.", "confirmation dialog", "dialog", "TmDialog"),
        R("focus-scope", "Focus scope", "Traps keyboard focus inside an overlay.", "focus trap", "zachyceni fokusu", "TmFocusScope"),
        R("sheet-handle", "Sheet handle", "Drag handle that changes a sheet height.", "drag handle", "tahlo panelu", "TmSheetHandle"),
        R("tooltip", "Tooltip", "Displays short contextual help.", "hint", "napoveda", "TmTooltip"),
        R("popover", "Popover", "Displays contextual floating content.", "floating panel", "plovouci panel", "TmPopover"),
        R("progress-bar", "Progress bar", "Shows completion progress.", "progress indicator", "prubeh", "TmProgressBar"),
        R("spinner", "Spinner", "Shows an indeterminate loading state.", "loading spinner", "nacitani", "TmSpinner"),
        R("skeleton", "Skeleton", "Shows placeholder shapes while content loads.", "loading placeholder", "kostra", "TmSkeleton"),
        R("toast-container", "Toast container", "Hosts transient toast notifications.", "toasts", "toast zpravy", "TmToastContainer"),
        R("notification-bell", "Notification bell", "Shows notification count and list access.", "notifications", "oznameni", "TmNotificationBell"),
        R("tabs", "Tabs", "Switches between panels in the same area.", "tab strip", "zalozky", "TmTabs", "TmTabPanel"),
        R("breadcrumbs", "Breadcrumbs", "Shows hierarchical navigation path.", "breadcrumb trail", "drobeckova navigace", "TmBreadcrumbs"),
        R("context-menu", "Context menu", "Shows actions for a selected target.", "right click menu", "kontextove menu", "TmContextMenu", "TmContextMenuItem"),
        R("bottom-navigation", "Bottom navigation", "Provides primary navigation along the bottom edge.", "bottom nav", "spodni navigace", "TmBottomNavigation"),
        R("action-bar", "Action bar", "Shows the primary actions of a component or view, typically pinned to the bottom edge on mobile.", "mobile action bar", "action buttons", "akcni lista", "TmMobileActionBar"),
        R("navigation-guard", "Navigation guard", "Confirms and gates navigation away from unsaved work.", "unsaved changes guard", "leave confirmation", "ochrana neulozenych zmen", "TmNavigationGuard"),
        R("scroll-spy-nav", "Scroll-spy navigation", "Highlights the current in-page section while scrolling and jumps to sections on click.", "section nav", "anchor nav", "navigace podle sekci", "TmScrollSpyNav"),
        R("menu", "Menu", "Displays navigation or command choices.", "navigation menu", "nabidka", "TmMenu"),
        R("navigation-bar", "Navigation bar", "Provides top-level page or app navigation.", "navbar", "top navigation", "navigacni lista", "TmNavbar", "TmTopBar"),
        R("sidebar", "Sidebar", "Provides side navigation or supporting panels.", "side nav", "bocni panel", "TmSidebar"),
        R("drawer", "Drawer", "Slides in a temporary side panel.", "slide panel", "vysuvny panel", "TmDrawer"),
        R("section", "Section", "Groups page content under a logical section.", "content section", "sekce", "TmSection"),
        R("command-palette", "Command palette", "Searches and runs commands.", "quick command", "paleta prikazu", "TmCommandPalette"),
        R("keyboard-shortcuts", "Keyboard shortcuts", "Displays available keyboard commands.", "shortcuts help", "klavesove zkratky", "TmKeyboardShortcutsHelp"),
        R("toolbar", "Toolbar", "Groups compact command buttons.", "tool bar", "lista nastroju", "TmToolbar", "TmToolbarButton", "TmToolbarDivider", "TmFormActionBar"),
        R("form-section", "Form section", "Groups related form fields.", "field group", "sekce formulare", "TmFormSection", "TmFormRow"),
        R("form-field", "Form field", "Wraps a labeled input and help or validation state.", "field wrapper", "pole formulare", "TmFormField", "TmValidatedField"),
        R("inline-edit", "Inline edit", "Edits a value directly in its display position.", "editable text", "uprava na miste", "TmInlineEdit"),
        R("validation-summary", "Validation summary", "Summarizes form validation errors.", "error summary", "souhrn validace", "TmValidationSummary"),
        R("dynamic-form", "Dynamic form", "Renders a form from metadata.", "generated form", "dynamicky formular", "TmDynamicFormRenderer"),
        R("validation-message", "Validation message", "Displays validation feedback for a field.", "field error", "validacni zprava", "TmFormValidationMessage"),
        R("file-drop", "File drop", "Accepts files by browse or drag-and-drop.", "file upload", "upload", "nahrani souboru", "TmFileDropZone", "TmFileUpload"),
        R("attachment-manager", "Attachment manager", "Lists and manages file attachments.", "attachments", "sprava priloh", "TmAttachmentManager"),
        R("chart", "Chart", "Visualizes data as a chart.", "graph", "graf", "TmChart", "TmCalendarHeatmap", "TmStockChart"),
        R("sparkline", "Sparkline", "Shows a compact inline trend chart.", "mini chart", "minigraf", "TmSparkline"),
        R("gauge", "Gauge", "Shows a value within a bounded range.", "meter", "meric", "TmGauge"),
        R("timeline", "Timeline", "Shows ordered events over time.", "activity timeline", "casova osa", "TmTimeline", "TmActivityTimeline"),
        R("stepper", "Stepper", "Shows progress through ordered steps.", "wizard steps", "kroky", "TmStepper"),
        R("scheduler", "Scheduler", "Displays calendar-based events or resources.", "schedule", "planovac", "TmScheduler"),
        R("dashboard", "Dashboard", "Displays a workspace of metrics and widgets.", "analytics board", "prehled", "TmDashboard", "TmWidgetSelector"),
        R("layout-observer", "Layout observer", "Resolves a container's responsive layout mode and cascades it to its children.", "responsive container", "pozorovatel rozlozeni", "TmLayoutObserver"),
        R("markdown-editor", "Markdown editor", "Edits markdown text.", "markdown input", "markdown editor", "TmMarkdownEditor"),
        R("code-editor", "Code editor", "Edits source code or JSON with monospace font and optional syntax highlighting.", "json editor", "editor kodu", "TmCodeEditor"),
        R("rich-text-editor", "Rich text editor", "Edits formatted rich text content.", "wysiwyg editor", "editor textu", "TmRichEditorFull", "TmRichEditorSimple"),
        R("spreadsheet", "Spreadsheet", "Displays and edits tabular worksheet data.", "worksheet", "tabulkovy procesor", "TmSpreadsheet"),
        R("diagram-editor", "Diagram editor", "Creates or edits visual diagrams and models.", "diagram canvas", "editor diagramu", "TmDiagramEditor", "TmModelingEditor"),
        R("image-gallery", "Image gallery", "Displays images in a browsable gallery.", "gallery", "galerie", "TmImageGallery", "TmLightbox"),
        R("filter-builder", "Filter builder", "Builds complex filter conditions.", "query builder", "tvorba filtru", "TmFilterBuilder"),
        R("pdf-viewer", "PDF viewer", "Displays a PDF document.", "document viewer", "prohlizec pdf", "TmPdfViewer"),
        R("pdf-annotator", "PDF annotator", "Annotates a PDF document with highlights, comments, stamps, and drawings.", "document markup", "anotace pdf", "TmPdfAnnotator"),
        R("audit-log", "Audit log", "Displays a filterable, virtualized log of audit events with detail diffs.", "activity log", "auditni zaznam", "TmAuditLogViewer"),
        R("deadline-calculator", "Deadline calculator", "Computes a deadline from a base date and a rule with business-day and holiday handling.", "date calculator", "vypocet terminu", "TmDeadlineCalculator"),
        R("ledger-grid", "Ledger grid", "Displays accounting movements with debit/credit/balance columns, totals, and matching.", "accounting table", "kniha pohybu", "TmLedgerGrid"),
        R("money-display", "Money display", "Displays a monetary amount with currency, sign, and locale formatting.", "amount", "castka", "TmMoneyDisplay"),
        R("kyc-wizard", "KYC wizard", "Guides identification of a person or company through steps: documents, addresses, ownership, declarations.", "compliance wizard", "identifikacni pruvodce", "TmKycWizard"),
        R("screening-result-panel", "Screening results", "Lists compliance screening findings with severity and confidence, and confirm/dismiss resolution.", "screening findings", "vysledky kontrol", "TmScreeningResultPanel"),
        R("data-import", "Data import", "Guides a file import: upload CSV/XLSX, map columns to a schema, dry-run validation, batched import with progress.", "import wizard", "import dat", "TmDataImport"),
        R("redaction-layer", "Redaction layer", "Marks rectangles over a document or image and exports a copy with the content destructively removed.", "blackout", "zacerneni", "TmRedactionLayer"),
        R("map", "Map", "Displays an interactive geographic map with markers or clusters.", "geographic map", "mapa", "TmMap"),
        R("editor-shell", "Editor shell", "Frames a canvas editor with header, toolbar, collapsible side panels, a status bar and mobile actions.", "editor frame", "editor layout", "editorovy ramec", "TmEditorShell"),
        R("side-panel", "Side panel", "Responsive inspector panel that docks in-flow on desktop and presents as a sheet on narrower containers.", "inspector panel", "properties panel", "bocni panel", "TmSidePanel")
    ];

    /// <inheritdoc/>
    public string SourceId => "BuiltIn";

    /// <inheritdoc/>
    public int Priority => 0;

    /// <inheritdoc/>
    public IEnumerable<UiRoleDefinition> GetRoles() => Roles;

    private static UiRoleDefinition R(
        string slug,
        string displayName,
        string definition,
        params string[] synonyms)
        => new(slug, displayName, definition, synonyms);
}
