using System.Reflection;
using System.Text.Json;
using FluentAssertions;
using Microsoft.AspNetCore.Components;
using Tempo.Blazor.Tests.Theme;

namespace Tempo.Blazor.Tests.Documentation;

/// <summary>
/// Freshness guard for the component JSON documentation an MCP client and the package docs serve.
/// <para>
/// The documentation set under <c>JsonDocumentation/</c> is regenerated by
/// <c>JsonDocumentationGenerator</c>, but regeneration is a manual step — a parameter added to a
/// component since the last run simply does not exist for a consumer reading the docs, and a renamed
/// parameter leaves behind a phantom entry describing an API the component no longer has. Nothing
/// compared the two sides until this test.
/// </para>
/// <para>
/// The population is derived by reflection — the same view a consumer gets — over every
/// <c>Tempo.*.dll</c> the test project references: every non-abstract, visible type derived from
/// <see cref="ComponentBase"/> is a component the library ships. The contract is EXACT: the set of
/// reflected component names must equal the set of <c>kind: "Component"</c> item names in the JSON,
/// modulo <see cref="UndocumentedComponents"/> — a frozen, itemized set that can only shrink by
/// writing the documentation, never grow by adding a component and staying silent. A documented
/// component that does not exist is a stale overlay and fails the same way a missing one does.
/// </para>
/// <para>
/// Nothing here is allowed to fail quietly: an assembly that will not load, a types listing that
/// comes back partial, and a JSON file that will not parse are all test failures, not skips —
/// each of them is exactly the hole a freshness guard exists to close.
/// </para>
/// <para>
/// Parameter sets are compared on both layers of the documentation model: overlay entries may not
/// name a parameter the component does not have (a stale name merges into the shipped bundle
/// verbatim), and each committed <c>tempo-blazor*.json</c> bundle must cover every settable
/// parameter of every component it carries — PER FILE, because a parameter missing from the one
/// bundle a consumer reads is not covered by a different bundle happening to name it — while
/// naming none that do not exist. A source change without a regeneration, or a stale overlay
/// entry, both fail here.
/// </para>
/// </summary>
public class ComponentDocumentationFreshnessTests
{
    /// <summary>
    /// Components that ship on the public surface but have no <c>kind: "Component"</c> JSON entry.
    /// The set is frozen: a component may leave it only by gaining documentation, and no component
    /// may enter it — a new component without documentation fails the population test below.
    /// </summary>
    private static readonly HashSet<string> UndocumentedComponents = new(StringComparer.Ordinal)
    {
        // FluentValidationValidator is a real component (ComponentBase, public, one [Parameter]),
        // but it lives in a .cs file, so the generator classifies it as a "Class" API item, not a
        // Component — the merge keeps the generated kind and no overlay can promote it. It is
        // documented in JsonDocumentation/Packages/Tempo.Blazor.FluentValidation/items/ as a Class.
        "FluentValidationValidator",
    };

    private static readonly HashSet<string> NonLibraryAssemblies = new(StringComparer.Ordinal)
    {
        "Tempo.Blazor.Tests",
        "Tempo.Blazor.Demo.Shared",
        "Tempo.Blazor.Demo.SharedUI",
    };

    /// <param name="Types">All component types sharing the item name — the library has exactly one
    /// such collision today (TmNotionEmojiPicker exists in a Shared/ and a UI/ variant); one doc
    /// entry must serve the union of their parameters.</param>
    private sealed record ComponentEntry(string Name, Type[] Types);

    private sealed record DocEntry(string File, HashSet<string> Parameters);

    private static string BaseName(string name)
    {
        var tick = name.IndexOf('`');
        return tick < 0 ? name : name[..tick];
    }

    private static bool IsParameter(PropertyInfo property)
        => property.GetCustomAttribute<ParameterAttribute>() is not null;

    /// <summary>Every public instance [Parameter] the component answers to, inherited included.</summary>
    private static string[] ReflectedParameters(Type type)
        => type.GetProperties(BindingFlags.Public | BindingFlags.Instance)
            .Where(IsParameter)
            .Select(p => p.Name)
            .Distinct(StringComparer.Ordinal)
            .OrderBy(n => n, StringComparer.Ordinal)
            .ToArray();

    private static string[] ReflectedParameters(ComponentEntry component)
        => component.Types.SelectMany(ReflectedParameters)
            .Distinct(StringComparer.Ordinal)
            .OrderBy(n => n, StringComparer.Ordinal)
            .ToArray();

    private static List<Assembly> LibraryAssemblies()
    {
        var assemblies = new List<Assembly>();
        foreach (var file in Directory.GetFiles(AppContext.BaseDirectory, "Tempo.*.dll"))
        {
            var name = Path.GetFileNameWithoutExtension(file);
            if (NonLibraryAssemblies.Contains(name))
            {
                continue;
            }

            try
            {
                assemblies.Add(Assembly.LoadFrom(file));
            }
            catch (Exception e)
            {
                // A package dll that will not load leaves its component surface unverifiable — the
                // guard cannot see what the docs must cover. That is a failure of the population,
                // not a reason to grade a partial one as complete.
                throw new InvalidOperationException(
                    $"library assembly '{name}' failed to load in the test host — its components are " +
                    "invisible to the documentation guard, so this is a failure, not a skip", e);
            }
        }

        return assemblies;
    }

    private static IReadOnlyList<Type> LoadableTypes(Assembly assembly)
    {
        try
        {
            return assembly.GetTypes();
        }
        catch (ReflectionTypeLoadException e)
        {
            // A partial type list is a silently smaller population — exactly what the exact-match
            // contract exists to catch, so surface it as a failure with the loader's own reasons
            // rather than grading the truncated view.
            var reasons = e.LoaderExceptions
                .Where(x => x is not null)
                .Select(x => x!.Message)
                .Distinct(StringComparer.Ordinal)
                .Take(5);
            throw new InvalidOperationException(
                $"assembly '{assembly.GetName().Name}' loaded only part of its types " +
                $"({e.Types.Count(t => t is null)} invisible): {string.Join("; ", reasons)}", e);
        }
    }

    /// <summary>
    /// The guard's denominator: every non-abstract, consumer-visible <see cref="ComponentBase"/>
    /// descendant in the library assemblies — the precise list of components a consumer can render,
    /// which is exactly the list the JSON documentation must name.
    /// </summary>
    private static List<ComponentEntry> ComponentPopulation()
        => LibraryAssemblies()
            .SelectMany(LoadableTypes)
            .Where(t => t is { IsAbstract: false, IsVisible: true }
                        && typeof(ComponentBase).IsAssignableFrom(t))
            .GroupBy(t => BaseName(t.Name), StringComparer.Ordinal)
            .Select(g => new ComponentEntry(g.Key, g.OrderBy(t => t.FullName, StringComparer.Ordinal).ToArray()))
            .OrderBy(e => e.Name, StringComparer.Ordinal)
            .ToList();

    /// <summary>
    /// Every <c>kind: "Component"</c> item anywhere under <c>JsonDocumentation/</c> — both the
    /// flat <c>Components/</c> overlays and the per-package <c>Packages/&lt;id&gt;/items/</c> tree —
    /// keyed by <c>itemName</c>. A name documented twice merges its parameter sets: the guard cares
    /// that the parameter is documented somewhere, not about which overlay won the merge.
    /// </summary>
    private static Dictionary<string, DocEntry> ComponentDocs()
    {
        var root = Path.Combine(ThemeCss.RepositoryRoot().FullName, "JsonDocumentation");
        var docs = new Dictionary<string, DocEntry>(StringComparer.Ordinal);
        foreach (var file in Directory.GetFiles(root, "*.json", SearchOption.AllDirectories))
        {
            JsonElement document;
            try
            {
                using var parsed = JsonDocument.Parse(File.ReadAllText(file));
                document = parsed.RootElement.Clone();
            }
            catch (JsonException e)
            {
                // A doc file that does not parse is a broken doc, not a missing one — say so.
                throw new InvalidOperationException(
                    $"documentation file is not valid JSON: {file}", e);
            }

            if (!document.TryGetProperty("kind", out var kind) || kind.GetString() != "Component"
                || !document.TryGetProperty("itemName", out var itemName))
            {
                continue;
            }

            var name = itemName.GetString();
            if (string.IsNullOrEmpty(name))
            {
                continue;
            }

            var parameters = new HashSet<string>(StringComparer.Ordinal);
            if (document.TryGetProperty("parameters", out var array) && array.ValueKind == JsonValueKind.Array)
            {
                foreach (var parameter in array.EnumerateArray())
                {
                    if (parameter.TryGetProperty("name", out var parameterName)
                        && parameterName.GetString() is { Length: > 0 } pn)
                    {
                        parameters.Add(pn);
                    }
                }
            }

            if (docs.TryGetValue(name, out var existing))
            {
                existing.Parameters.UnionWith(parameters);
            }
            else
            {
                docs[name] = new DocEntry(file, parameters);
            }
        }

        return docs;
    }

    /// <summary>
    /// Names of every documented TYPE, any kind — used to attribute inherited parameters to the
    /// base that documents them (e.g. <c>DataTestId</c> lives on <c>TmComponentBase</c>'s entry, not
    /// repeated in 162 derived components).
    /// </summary>
    private static HashSet<string> DocumentedTypeNames()
        => new(DocumentedTypeMembers().Keys, StringComparer.Ordinal);

    /// <summary>
    /// The member names each documented type's own page carries, keyed by <c>itemName</c> and merged
    /// across every file that names it — <c>parameters[].name</c> for component entries and
    /// <c>members[].name</c> for class entries, over BOTH the <c>JsonDocumentation/</c> overlays and
    /// the committed <c>tempo-*.json</c> bundles. This is the coverage view
    /// <see cref="Documented_Ancestor_Pages_Name_The_Parameters_They_Declare"/> checks attribution
    /// against: ancestor attribution is only sound when the ancestor's page actually NAMES the
    /// parameter somewhere a consumer reads.
    /// </summary>
    private static Dictionary<string, HashSet<string>> DocumentedTypeMembers()
    {
        var members = new Dictionary<string, HashSet<string>>(StringComparer.Ordinal);
        CollectDocumentedTypeMembers(
            Path.Combine(ThemeCss.RepositoryRoot().FullName, "JsonDocumentation"), "*.json",
            SearchOption.AllDirectories, members);
        CollectDocumentedTypeMembers(
            ThemeCss.RepositoryRoot().FullName, "tempo-*.json",
            SearchOption.TopDirectoryOnly, members);
        return members;
    }

    private static void CollectDocumentedTypeMembers(
        string directory, string pattern, SearchOption option,
        Dictionary<string, HashSet<string>> members)
    {
        foreach (var file in Directory.GetFiles(directory, pattern, option))
        {
            JsonElement document;
            try
            {
                using var parsed = JsonDocument.Parse(File.ReadAllText(file));
                document = parsed.RootElement.Clone();
            }
            catch (JsonException e)
            {
                throw new InvalidOperationException(
                    $"documentation file is not valid JSON: {file}", e);
            }

            CollectDocumentedTypeMembers(document, members);
        }
    }

    private static void CollectDocumentedTypeMembers(
        JsonElement element, Dictionary<string, HashSet<string>> members)
    {
        switch (element.ValueKind)
        {
            case JsonValueKind.Object:
                if (element.TryGetProperty("itemName", out var itemName)
                    && itemName.GetString() is { Length: > 0 } name)
                {
                    var set = members.TryGetValue(name, out var existing)
                        ? existing
                        : members[name] = new HashSet<string>(StringComparer.Ordinal);
                    AddMemberNames(element, "parameters", set);
                    AddMemberNames(element, "members", set);
                }
                else
                {
                    foreach (var property in element.EnumerateObject())
                    {
                        CollectDocumentedTypeMembers(property.Value, members);
                    }
                }

                break;
            case JsonValueKind.Array:
                foreach (var item in element.EnumerateArray())
                {
                    CollectDocumentedTypeMembers(item, members);
                }

                break;
        }
    }

    private static void AddMemberNames(JsonElement item, string arrayName, HashSet<string> set)
    {
        if (item.TryGetProperty(arrayName, out var array) && array.ValueKind == JsonValueKind.Array)
        {
            foreach (var member in array.EnumerateArray())
            {
                if (member.TryGetProperty("name", out var memberName)
                    && memberName.GetString() is { Length: > 0 } n)
                {
                    set.Add(n);
                }
            }
        }
    }

    /// <summary>
    /// Parameters the shipped documentation must name for this component: everything on its public
    /// surface EXCEPT <c>[Parameter(CaptureUnmatchedValues)]</c> splats — the generator's own
    /// convention never emits them — and names declared on an ancestor that has a documentation
    /// entry of its own (those are attributed to the base's page, as the merge pipeline does).
    /// </summary>
    private static string[] ExpectedParameters(ComponentEntry component, HashSet<string> documentedTypes)
        => component.Types.SelectMany(t => t.GetProperties(BindingFlags.Public | BindingFlags.Instance))
            .Where(IsParameter)
            .Where(p => p.GetCustomAttribute<ParameterAttribute>()!.CaptureUnmatchedValues is false)
            .Where(p => p.DeclaringType is null
                        || component.Types.Contains(p.DeclaringType)
                        || !documentedTypes.Contains(BaseName(p.DeclaringType.Name)))
            .Select(p => p.Name)
            .Distinct(StringComparer.Ordinal)
            .OrderBy(n => n, StringComparer.Ordinal)
            .ToArray();

    /// <summary>
    /// The guard's denominator is the documentation list itself: every visible
    /// <see cref="ComponentBase"/> descendant must be named in the JSON, and every
    /// <c>kind: "Component"</c> name in the JSON must be a component that exists. There is no
    /// floor and no direction the check can silently shrink in — a reflection scan that sees
    /// nothing, a deleted component whose overlay survived, and a documented name with no type
    /// all fail here, by name.
    /// </summary>
    [Fact]
    public void Population_Is_Exactly_The_Documented_Component_List()
    {
        var population = ComponentPopulation().Select(c => c.Name).ToHashSet(StringComparer.Ordinal);
        var documented = ComponentDocs().Keys;

        var undocumented = population.Except(documented).OrderBy(n => n, StringComparer.Ordinal).ToList();
        var phantom = documented.Except(population).OrderBy(n => n, StringComparer.Ordinal).ToList();

        undocumented.Should().BeEquivalentTo(UndocumentedComponents.OrderBy(n => n, StringComparer.Ordinal),
            "the set of components without a kind:\"Component\" JSON entry is frozen and itemized — " +
            "a new undocumented component must be documented (the set never grows), and a member that " +
            "is documented now must leave it (the set only shrinks)");
        phantom.Should().BeEmpty(
            "a kind:\"Component\" entry for a type that no longer exists is a stale overlay promising " +
            "an API nothing ships — delete it: " + string.Join(", ", phantom.Take(20)));
    }

    [Fact]
    public void Documented_Parameters_Exist_On_The_Component()
    {
        var docs = ComponentDocs();

        var phantom = ComponentPopulation()
            .Where(c => docs.TryGetValue(c.Name, out _))
            .SelectMany(c =>
            {
                var real = ReflectedParameters(c).ToHashSet(StringComparer.Ordinal);
                return docs[c.Name].Parameters
                    .Where(name => !real.Contains(name))
                    .Select(name => $"{c.Name}.{name} ({Path.GetFileName(docs[c.Name].File)})");
            })
            .OrderBy(s => s, StringComparer.Ordinal)
            .ToList();

        phantom.Should().BeEmpty(
            "a documented parameter that no longer exists is a stale API promise, not documentation: "
            + string.Join(", ", phantom.Take(20)));
    }

    /// <summary>
    /// The shipped per-package bundles (<c>tempo-blazor*.json</c>) are what a consumer actually
    /// reads. Coverage is asserted PER FILE: every bundle that carries a component entry must name
    /// every parameter declared on that component — a gap filled only inside a different bundle is
    /// still a gap in the file the consumer opened. A population component absent from every bundle
    /// fails the same way.
    /// <para>
    /// The expected set excludes <c>[Parameter(CaptureUnmatchedValues)]</c> properties (the
    /// generator's own convention skips the <c>@attributes</c> splat) and parameters declared on a
    /// documented ancestor — those live on the ancestor's entry, e.g. <c>TmComponentBase</c>'s
    /// <c>DataTestId</c>.
    /// </para>
    /// </summary>
    [Fact]
    public void Bundle_Covers_Every_Component_Parameter()
    {
        var bundles = BundleDocs();
        var documentedTypes = DocumentedTypeNames();

        var missing = ComponentPopulation()
            .Where(c => !UndocumentedComponents.Contains(c.Name))
            .SelectMany(c =>
            {
                var expected = ExpectedParameters(c, documentedTypes);
                var carriers = bundles
                    .Where(kv => kv.Value.ContainsKey(c.Name))
                    .Select(kv => kv.Key)
                    .ToList();
                if (carriers.Count == 0)
                {
                    return expected.Select(name =>
                        $"{c.Name}.{name} — component has no kind:\"Component\" entry in any tempo-*.json bundle");
                }

                return carriers.SelectMany(file =>
                {
                    var entry = bundles[file][c.Name];
                    return expected
                        .Where(name => !entry.Parameters.Contains(name))
                        .Select(name => $"{file}: {c.Name}.{name}");
                });
            })
            .OrderBy(s => s, StringComparer.Ordinal)
            .ToList();

        missing.Should().BeEmpty(
            "a parameter a consumer can set must appear in every bundle file that carries the "
            + "component — regenerate tempo-blazor*.json after changing [Parameter] surface: "
            + string.Join(", ", missing.Take(20)));
    }

    /// <summary>
    /// The bundle-level guard above cannot see overlay drift: the merge pipeline builds bundles
    /// from reflection first and only enriches from the overlay files, so a parameter missing
    /// under <c>JsonDocumentation/</c> still reaches the shipped bundle with a bare generated
    /// entry — documented nowhere a maintainer can edit. This is the fourth combination the
    /// 2026-09-22 review (N201) found unguarded: the overlay set itself must name every settable
    /// parameter, merged across <c>Components/</c> and <c>Packages/&lt;id&gt;/items/</c>.
    /// </summary>
    [Fact]
    public void Overlay_Covers_Every_Component_Parameter()
    {
        var docs = ComponentDocs();
        var documentedTypes = DocumentedTypeNames();

        var missing = ComponentPopulation()
            .Where(c => !UndocumentedComponents.Contains(c.Name))
            .SelectMany(c =>
            {
                var expected = ExpectedParameters(c, documentedTypes);
                if (!docs.TryGetValue(c.Name, out var entry))
                {
                    return expected.Select(name =>
                        $"{c.Name}.{name} — component has no kind:\"Component\" entry under JsonDocumentation/");
                }

                return expected
                    .Where(name => !entry.Parameters.Contains(name))
                    .Select(name => $"{Path.GetFileName(entry.File)}: {c.Name}.{name}");
            })
            .OrderBy(s => s, StringComparer.Ordinal)
            .ToList();

        missing.Should().BeEmpty(
            "a parameter a consumer can set must appear in the component's own JsonDocumentation/ "
            + "overlay file — the bundle-level guard reflects live params even when the overlay page "
            + "drifted, so this direction needs its own check: "
            + string.Join(", ", missing.Take(20)));
    }

    /// <summary>
    /// <see cref="ExpectedParameters"/> attributes a parameter declared on an ancestor to the
    /// ancestor's own documentation page — but until this check nothing verified the page actually
    /// carries it. A bare generated entry is enough to launder the whole inherited surface: the
    /// leaf components report no missing parameters (all attributed away) and the ancestor's page
    /// names none of them, so the parameters are documented NOWHERE while every guard stays green.
    /// That is precisely what happened to the seven parameters of <c>TmNotionDbCellBase</c>
    /// (20C review carry-forward): <c>Field</c>, <c>Value</c>, <c>ReadOnly</c>, <c>IsEditing</c>,
    /// <c>OnCommit</c>, <c>OnCancel</c> and <c>OnEditRequested</c> were absent from every overlay and
    /// every shipped bundle — invisible to consumers on ~20 cell components.
    /// </summary>
    /// <para>
    /// The check walks the ancestor chain of every population component and, for each ancestor
    /// that owns at least one settable <c>[Parameter]</c> AND has a documentation entry of its
    /// own, requires the entry to name each parameter the ancestor declares — in
    /// <c>parameters</c> or <c>members</c>, on the overlay or in a bundle. An ancestor with no
    /// entry at all stays the leaf's responsibility under <see cref="ExpectedParameters"/>;
    /// this fact only removes the free pass a contentless entry used to grant.
    /// </para>
    [Fact]
    public void Documented_Ancestor_Pages_Name_The_Parameters_They_Declare()
    {
        var documentedMembers = DocumentedTypeMembers();

        var missing = ComponentPopulation()
            .SelectMany(c => c.Types)
            .SelectMany(AncestorChain)
            .Where(ancestor => documentedMembers.ContainsKey(BaseName(ancestor.Name)))
            .SelectMany(ancestor => ancestor
                .GetProperties(BindingFlags.Public | BindingFlags.Instance)
                .Where(IsParameter)
                .Where(p => p.DeclaringType == ancestor)
                .Where(p => p.GetCustomAttribute<ParameterAttribute>()!.CaptureUnmatchedValues is false)
                .Where(p => !documentedMembers[BaseName(ancestor.Name)].Contains(p.Name))
                .Select(p => $"{BaseName(ancestor.Name)}.{p.Name}"))
            .Distinct(StringComparer.Ordinal)
            .OrderBy(s => s, StringComparer.Ordinal)
            .ToList();

        missing.Should().BeEmpty(
            "a parameter declared on a documented ancestor must be named on that ancestor's own "
            + "page — attribution only moves the obligation, it cannot fulfil it. Document the "
            + "member (XML doc on the declaration regenerates 'members'; a hand-maintained entry "
            + "may list it too) or the leaf components inherit an invisible parameter: "
            + string.Join(", ", missing.Take(20)));
    }

    /// <summary>
    /// Every type the component inherits from, nearest first, stopping below
    /// <see cref="ComponentBase"/> — the framework base carries no <c>[Parameter]</c>s and the
    /// walk has nowhere left to go.
    /// </summary>
    private static IEnumerable<Type> AncestorChain(Type type)
    {
        for (var ancestor = type.BaseType;
             ancestor is not null && ancestor != typeof(ComponentBase) && ancestor != typeof(object);
             ancestor = ancestor.BaseType)
        {
            yield return ancestor;
        }
    }

    [Fact]
    public void Bundle_Documents_No_Phantom_Parameters()
    {
        var bundles = BundleDocs();
        var population = ComponentPopulation().ToDictionary(c => c.Name, StringComparer.Ordinal);

        var phantom = bundles
            .SelectMany(kv => kv.Value
                .Where(item => population.ContainsKey(item.Key))
                .SelectMany(item =>
                {
                    var real = ReflectedParameters(population[item.Key]).ToHashSet(StringComparer.Ordinal);
                    return item.Value.Parameters
                        .Where(name => !real.Contains(name))
                        .Select(name => $"{kv.Key}: {item.Key}.{name}");
                }))
            .OrderBy(s => s, StringComparer.Ordinal)
            .ToList();

        phantom.Should().BeEmpty(
            "a bundle file naming a parameter the component does not have is a stale overlay or a "
            + "stale bundle — the file name is in each entry: " + string.Join(", ", phantom.Take(20)));
    }

    /// <summary>
    /// The other direction of the per-file contract: a <c>kind: "Component"</c> item inside a
    /// shipped bundle whose name no <see cref="ComponentBase"/> descendant answers to is a phantom —
    /// the surviving overlay of a deleted component, shipped to consumers as if it still existed.
    /// </summary>
    [Fact]
    public void Bundle_Contains_No_Phantom_Components()
    {
        var bundles = BundleDocs();
        var population = ComponentPopulation().Select(c => c.Name).ToHashSet(StringComparer.Ordinal);

        var phantom = bundles
            .SelectMany(kv => kv.Value.Keys
                .Where(name => !population.Contains(name))
                .Select(name => $"{kv.Key}: {name}"))
            .OrderBy(s => s, StringComparer.Ordinal)
            .ToList();

        phantom.Should().BeEmpty(
            "a bundle entry for a component that does not exist is a stale doc shipped to consumers — "
            + "delete the orphan overlay and regenerate: " + string.Join(", ", phantom.Take(20)));
    }

    /// <summary>
    /// Every <c>kind: "Component"</c> item inside each committed <c>tempo-blazor*.json</c> bundle at
    /// the repository root, keyed by file name and then by <c>itemName</c>. Assertions run per file —
    /// merging the bundles into one map would let an entry that is complete in one file launder the
    /// same entry being incomplete in another. The aggregate document nests items under
    /// <c>packages[].items</c>, so the search is recursive rather than top-level.
    /// </summary>
    private static IReadOnlyDictionary<string, Dictionary<string, DocEntry>> BundleDocs()
    {
        var root = ThemeCss.RepositoryRoot().FullName;
        var docs = new Dictionary<string, Dictionary<string, DocEntry>>(StringComparer.Ordinal);
        foreach (var file in Directory.GetFiles(root, "tempo-*.json", SearchOption.TopDirectoryOnly)
                     .OrderBy(f => f, StringComparer.Ordinal))
        {
            JsonElement document;
            try
            {
                using var parsed = JsonDocument.Parse(File.ReadAllText(file));
                document = parsed.RootElement.Clone();
            }
            catch (JsonException e)
            {
                throw new InvalidOperationException(
                    $"committed bundle is not valid JSON: {Path.GetFileName(file)}", e);
            }

            var fileDocs = new Dictionary<string, DocEntry>(StringComparer.Ordinal);
            CollectComponentItems(document, file, fileDocs);
            docs[Path.GetFileName(file)] = fileDocs;
        }

        return docs;
    }

    private static void CollectComponentItems(
        JsonElement element, string file, Dictionary<string, DocEntry> docs)
    {
        switch (element.ValueKind)
        {
            case JsonValueKind.Object:
                if (element.TryGetProperty("kind", out var kind)
                    && kind.ValueKind == JsonValueKind.String
                    && kind.GetString() == "Component"
                    && element.TryGetProperty("itemName", out var itemName)
                    && itemName.GetString() is { Length: > 0 } name)
                {
                    var parameters = new HashSet<string>(StringComparer.Ordinal);
                    if (element.TryGetProperty("parameters", out var array)
                        && array.ValueKind == JsonValueKind.Array)
                    {
                        foreach (var parameter in array.EnumerateArray())
                        {
                            if (parameter.TryGetProperty("name", out var pn)
                                && pn.GetString() is { Length: > 0 } p)
                            {
                                parameters.Add(p);
                            }
                        }
                    }

                    if (docs.TryGetValue(name, out var existing))
                    {
                        existing.Parameters.UnionWith(parameters);
                    }
                    else
                    {
                        docs[name] = new DocEntry(file, parameters);
                    }
                }
                else
                {
                    foreach (var property in element.EnumerateObject())
                    {
                        CollectComponentItems(property.Value, file, docs);
                    }
                }

                break;
            case JsonValueKind.Array:
                foreach (var item in element.EnumerateArray())
                {
                    CollectComponentItems(item, file, docs);
                }

                break;
        }
    }
}
