using System.Reflection;
using System.Text.Json;
using FluentAssertions;
using Microsoft.AspNetCore.Components;
using Tempo.Blazor.Tests.Theme;

namespace Tempo.Blazor.Tests.Documentation;

/// <summary>
/// Freshness guard for the component JSON documentation an MCP client and the package docs serve.
/// <para>
/// The documentation set under <c>JsonDocumentation/</c> is regenerated by
/// <c>JsonDocumentationGenerator</c>, but regeneration is a manual step — a parameter added to a
/// component since the last run simply does not exist for a consumer reading the docs, and a renamed
/// parameter leaves behind a phantom entry describing an API the component no longer has. Nothing
/// compared the two sides until this test.
/// </para>
/// <para>
/// The population is derived by reflection — the same view a consumer gets — over every
/// <c>Tempo.*.dll</c> the test project references: every non-abstract, visible type derived from
/// <see cref="ComponentBase"/> is a component the library ships. The contract is EXACT: the set of
/// reflected component names must equal the set of <c>kind: "Component"</c> item names in the JSON,
/// modulo <see cref="UndocumentedComponents"/> — a frozen, itemized set that can only shrink by
/// writing the documentation, never grow by adding a component and staying silent. A documented
/// component that does not exist is a stale overlay and fails the same way a missing one does.
/// </para>
/// <para>
/// Nothing here is allowed to fail quietly: an assembly that will not load, a types listing that
/// comes back partial, and a JSON file that will not parse are all test failures, not skips —
/// each of them is exactly the hole a freshness guard exists to close.
/// </para>
/// <para>
/// Parameter sets are compared on both layers of the documentation model: overlay entries may not
/// name a parameter the component does not have (a stale name merges into the shipped bundle
/// verbatim), and each committed <c>tempo-blazor*.json</c> bundle must cover every settable
/// parameter of every component it carries — PER FILE, because a parameter missing from the one
/// bundle a consumer reads is not covered by a different bundle happening to name it — while
/// naming none that do not exist. A source change without a regeneration, or a stale overlay
/// entry, both fail here.
/// </para>
/// </summary>
public class ComponentDocumentationFreshnessTests
{
    /// <summary>
    /// Components that ship on the public surface but have no <c>kind: "Component"</c> JSON entry.
    /// The set is frozen: a component may leave it only by gaining documentation, and no component
    /// may enter it — a new component without documentation fails the population test below.
    /// </summary>
    private static readonly HashSet<string> UndocumentedComponents = new(StringComparer.Ordinal)
    {
        // FluentValidationValidator is a real component (ComponentBase, public, one [Parameter]),
        // but it lives in a .cs file, so the generator classifies it as a "Class" API item, not a
        // Component — the merge keeps the generated kind and no overlay can promote it. It is
        // documented in JsonDocumentation/Packages/Tempo.Blazor.FluentValidation/items/ as a Class.
        "FluentValidationValidator",
    };

    private static readonly HashSet<string> NonLibraryAssemblies = new(StringComparer.Ordinal)
    {
        "Tempo.Blazor.Tests",
        "Tempo.Blazor.Demo.Shared",
        "Tempo.Blazor.Demo.SharedUI",
    };

    /// <param name="Types">All component types sharing the item name — the library has exactly one
    /// such collision today (TmNotionEmojiPicker exists in a Shared/ and a UI/ variant); one doc
    /// entry must serve the union of their parameters.</param>
    private sealed record ComponentEntry(string Name, Type[] Types);

    private sealed record DocEntry(string File, HashSet<string> Parameters);

    private static string BaseName(string name)
    {
        var tick = name.IndexOf('`');
        return tick < 0 ? name : name[..tick];
    }

    private static bool IsParameter(PropertyInfo property)
        => property.GetCustomAttribute<ParameterAttribute>() is not null;

    /// <summary>Every public instance [Parameter] the component answers to, inherited included.</summary>
    private static string[] ReflectedParameters(Type type)
        => type.GetProperties(BindingFlags.Public | BindingFlags.Instance)
            .Where(IsParameter)
            .Select(p => p.Name)
            .Distinct(StringComparer.Ordinal)
            .OrderBy(n => n, StringComparer.Ordinal)
            .ToArray();

    private static string[] ReflectedParameters(ComponentEntry component)
        => component.Types.SelectMany(ReflectedParameters)
            .Distinct(StringComparer.Ordinal)
            .OrderBy(n => n, StringComparer.Ordinal)
            .ToArray();

    private static List<Assembly> LibraryAssemblies()
    {
        var assemblies = new List<Assembly>();
        foreach (var file in Directory.GetFiles(AppContext.BaseDirectory, "Tempo.*.dll"))
        {
            var name = Path.GetFileNameWithoutExtension(file);
            if (NonLibraryAssemblies.Contains(name))
            {
                continue;
            }

            try
            {
                assemblies.Add(Assembly.LoadFrom(file));
            }
            catch (Exception e)
            {
                // A package dll that will not load leaves its component surface unverifiable — the
                // guard cannot see what the docs must cover. That is a failure of the population,
                // not a reason to grade a partial one as complete.
                throw new InvalidOperationException(
                    $"library assembly '{name}' failed to load in the test host — its components are " +
                    "invisible to the documentation guard, so this is a failure, not a skip", e);
            }
        }

        return assemblies;
    }

    private static IReadOnlyList<Type> LoadableTypes(Assembly assembly)
    {
        try
        {
            return assembly.GetTypes();
        }
        catch (ReflectionTypeLoadException e)
        {
            // A partial type list is a silently smaller population — exactly what the exact-match
            // contract exists to catch, so surface it as a failure with the loader's own reasons
            // rather than grading the truncated view.
            var reasons = e.LoaderExceptions
                .Where(x => x is not null)
                .Select(x => x!.Message)
                .Distinct(StringComparer.Ordinal)
                .Take(5);
            throw new InvalidOperationException(
                $"assembly '{assembly.GetName().Name}' loaded only part of its types " +
                $"({e.Types.Count(t => t is null)} invisible): {string.Join("; ", reasons)}", e);
        }
    }

    /// <summary>
    /// The guard's denominator: every non-abstract, consumer-visible <see cref="ComponentBase"/>
    /// descendant in the library assemblies — the precise list of components a consumer can render,
    /// which is exactly the list the JSON documentation must name.
    /// </summary>
    private static List<ComponentEntry> ComponentPopulation()
        => LibraryAssemblies()
            .SelectMany(LoadableTypes)
            .Where(t => t is { IsAbstract: false, IsVisible: true }
                        && typeof(ComponentBase).IsAssignableFrom(t))
            .GroupBy(t => BaseName(t.Name), StringComparer.Ordinal)
            .Select(g => new ComponentEntry(g.Key, g.OrderBy(t => t.FullName, StringComparer.Ordinal).ToArray()))
            .OrderBy(e => e.Name, StringComparer.Ordinal)
            .ToList();

    /// <summary>
    /// Every <c>kind: "Component"</c> item anywhere under <c>JsonDocumentation/</c> — both the
    /// flat <c>Components/</c> overlays and the per-package <c>Packages/&lt;id&gt;/items/</c> tree —
    /// keyed by <c>itemName</c>. A name documented twice merges its parameter sets: the guard cares
    /// that the parameter is documented somewhere, not about which overlay won the merge.
    /// </summary>
    private static Dictionary<string, DocEntry> ComponentDocs()
    {
        var root = Path.Combine(ThemeCss.RepositoryRoot().FullName, "JsonDocumentation");
        var docs = new Dictionary<string, DocEntry>(StringComparer.Ordinal);
        foreach (var file in Directory.GetFiles(root, "*.json", SearchOption.AllDirectories))
        {
            JsonElement document;
            try
            {
                using var parsed = JsonDocument.Parse(File.ReadAllText(file));
                document = parsed.RootElement.Clone();
            }
            catch (JsonException e)
            {
                // A doc file that does not parse is a broken doc, not a missing one — say so.
                throw new InvalidOperationException(
                    $"documentation file is not valid JSON: {file}", e);
            }

            if (!document.TryGetProperty("kind", out var kind) || kind.GetString() != "Component"
                || !document.TryGetProperty("itemName", out var itemName))
            {
                continue;
            }

            var name = itemName.GetString();
            if (string.IsNullOrEmpty(name))
            {
                continue;
            }

            var parameters = new HashSet<string>(StringComparer.Ordinal);
            if (document.TryGetProperty("parameters", out var array) && array.ValueKind == JsonValueKind.Array)
            {
                foreach (var parameter in array.EnumerateArray())
                {
                    if (parameter.TryGetProperty("name", out var parameterName)
                        && parameterName.GetString() is { Length: > 0 } pn)
                    {
                        parameters.Add(pn);
                    }
                }
            }

            if (docs.TryGetValue(name, out var existing))
            {
                existing.Parameters.UnionWith(parameters);
            }
            else
            {
                docs[name] = new DocEntry(file, parameters);
            }
        }

        return docs;
    }

    /// <summary>
    /// Names of every documented TYPE, any kind — used to attribute inherited parameters to the
    /// base that documents them (e.g. <c>DataTestId</c> lives on <c>TmComponentBase</c>'s entry, not
    /// repeated in 162 derived components).
    /// </summary>
    private static HashSet<string> DocumentedTypeNames()
    {
        var root = Path.Combine(ThemeCss.RepositoryRoot().FullName, "JsonDocumentation");
        var names = new HashSet<string>(StringComparer.Ordinal);
        foreach (var file in Directory.GetFiles(root, "*.json", SearchOption.AllDirectories))
        {
            try
            {
                using var parsed = JsonDocument.Parse(File.ReadAllText(file));
                if (parsed.RootElement.TryGetProperty("itemName", out var itemName)
                    && itemName.GetString() is { Length: > 0 } name)
                {
                    names.Add(name);
                }
            }
            catch (JsonException e)
            {
                throw new InvalidOperationException(
                    $"documentation file is not valid JSON: {file}", e);
            }
        }

        return names;
    }

    /// <summary>
    /// Parameters the shipped documentation must name for this component: everything on its public
    /// surface EXCEPT <c>[Parameter(CaptureUnmatchedValues)]</c> splats — the generator's own
    /// convention never emits them — and names declared on an ancestor that has a documentation
    /// entry of its own (those are attributed to the base's page, as the merge pipeline does).
    /// </summary>
    private static string[] ExpectedParameters(ComponentEntry component, HashSet<string> documentedTypes)
        => component.Types.SelectMany(t => t.GetProperties(BindingFlags.Public | BindingFlags.Instance))
            .Where(IsParameter)
            .Where(p => p.GetCustomAttribute<ParameterAttribute>()!.CaptureUnmatchedValues is false)
            .Where(p => p.DeclaringType is null
                        || component.Types.Contains(p.DeclaringType)
                        || !documentedTypes.Contains(BaseName(p.DeclaringType.Name)))
            .Select(p => p.Name)
            .Distinct(StringComparer.Ordinal)
            .OrderBy(n => n, StringComparer.Ordinal)
            .ToArray();

    /// <summary>
    /// The guard's denominator is the documentation list itself: every visible
    /// <see cref="ComponentBase"/> descendant must be named in the JSON, and every
    /// <c>kind: "Component"</c> name in the JSON must be a component that exists. There is no
    /// floor and no direction the check can silently shrink in — a reflection scan that sees
    /// nothing, a deleted component whose overlay survived, and a documented name with no type
    /// all fail here, by name.
    /// </summary>
    [Fact]
    public void Population_Is_Exactly_The_Documented_Component_List()
    {
        var population = ComponentPopulation().Select(c => c.Name).ToHashSet(StringComparer.Ordinal);
        var documented = ComponentDocs().Keys;

        var undocumented = population.Except(documented).OrderBy(n => n, StringComparer.Ordinal).ToList();
        var phantom = documented.Except(population).OrderBy(n => n, StringComparer.Ordinal).ToList();

        undocumented.Should().BeEquivalentTo(UndocumentedComponents.OrderBy(n => n, StringComparer.Ordinal),
            "the set of components without a kind:\"Component\" JSON entry is frozen and itemized — " +
            "a new undocumented component must be documented (the set never grows), and a member that " +
            "is documented now must leave it (the set only shrinks)");
        phantom.Should().BeEmpty(
            "a kind:\"Component\" entry for a type that no longer exists is a stale overlay promising " +
            "an API nothing ships — delete it: " + string.Join(", ", phantom.Take(20)));
    }

    [Fact]
    public void Documented_Parameters_Exist_On_The_Component()
    {
        var docs = ComponentDocs();

        var phantom = ComponentPopulation()
            .Where(c => docs.TryGetValue(c.Name, out _))
            .SelectMany(c =>
            {
                var real = ReflectedParameters(c).ToHashSet(StringComparer.Ordinal);
                return docs[c.Name].Parameters
                    .Where(name => !real.Contains(name))
                    .Select(name => $"{c.Name}.{name} ({Path.GetFileName(docs[c.Name].File)})");
            })
            .OrderBy(s => s, StringComparer.Ordinal)
            .ToList();

        phantom.Should().BeEmpty(
            "a documented parameter that no longer exists is a stale API promise, not documentation: "
            + string.Join(", ", phantom.Take(20)));
    }

    /// <summary>
    /// The shipped per-package bundles (<c>tempo-blazor*.json</c>) are what a consumer actually
    /// reads. Coverage is asserted PER FILE: every bundle that carries a component entry must name
    /// every parameter declared on that component — a gap filled only inside a different bundle is
    /// still a gap in the file the consumer opened. A population component absent from every bundle
    /// fails the same way.
    /// <para>
    /// The expected set excludes <c>[Parameter(CaptureUnmatchedValues)]</c> properties (the
    /// generator's own convention skips the <c>@attributes</c> splat) and parameters declared on a
    /// documented ancestor — those live on the ancestor's entry, e.g. <c>TmComponentBase</c>'s
    /// <c>DataTestId</c>.
    /// </para>
    /// </summary>
    [Fact]
    public void Bundle_Covers_Every_Component_Parameter()
    {
        var bundles = BundleDocs();
        var documentedTypes = DocumentedTypeNames();

        var missing = ComponentPopulation()
            .Where(c => !UndocumentedComponents.Contains(c.Name))
            .SelectMany(c =>
            {
                var expected = ExpectedParameters(c, documentedTypes);
                var carriers = bundles
                    .Where(kv => kv.Value.ContainsKey(c.Name))
                    .Select(kv => kv.Key)
                    .ToList();
                if (carriers.Count == 0)
                {
                    return expected.Select(name =>
                        $"{c.Name}.{name} — component has no kind:\"Component\" entry in any tempo-*.json bundle");
                }

                return carriers.SelectMany(file =>
                {
                    var entry = bundles[file][c.Name];
                    return expected
                        .Where(name => !entry.Parameters.Contains(name))
                        .Select(name => $"{file}: {c.Name}.{name}");
                });
            })
            .OrderBy(s => s, StringComparer.Ordinal)
            .ToList();

        missing.Should().BeEmpty(
            "a parameter a consumer can set must appear in every bundle file that carries the "
            + "component — regenerate tempo-blazor*.json after changing [Parameter] surface: "
            + string.Join(", ", missing.Take(20)));
    }

    [Fact]
    public void Bundle_Documents_No_Phantom_Parameters()
    {
        var bundles = BundleDocs();
        var population = ComponentPopulation().ToDictionary(c => c.Name, StringComparer.Ordinal);

        var phantom = bundles
            .SelectMany(kv => kv.Value
                .Where(item => population.ContainsKey(item.Key))
                .SelectMany(item =>
                {
                    var real = ReflectedParameters(population[item.Key]).ToHashSet(StringComparer.Ordinal);
                    return item.Value.Parameters
                        .Where(name => !real.Contains(name))
                        .Select(name => $"{kv.Key}: {item.Key}.{name}");
                }))
            .OrderBy(s => s, StringComparer.Ordinal)
            .ToList();

        phantom.Should().BeEmpty(
            "a bundle file naming a parameter the component does not have is a stale overlay or a "
            + "stale bundle — the file name is in each entry: " + string.Join(", ", phantom.Take(20)));
    }

    /// <summary>
    /// The other direction of the per-file contract: a <c>kind: "Component"</c> item inside a
    /// shipped bundle whose name no <see cref="ComponentBase"/> descendant answers to is a phantom —
    /// the surviving overlay of a deleted component, shipped to consumers as if it still existed.
    /// </summary>
    [Fact]
    public void Bundle_Contains_No_Phantom_Components()
    {
        var bundles = BundleDocs();
        var population = ComponentPopulation().Select(c => c.Name).ToHashSet(StringComparer.Ordinal);

        var phantom = bundles
            .SelectMany(kv => kv.Value.Keys
                .Where(name => !population.Contains(name))
                .Select(name => $"{kv.Key}: {name}"))
            .OrderBy(s => s, StringComparer.Ordinal)
            .ToList();

        phantom.Should().BeEmpty(
            "a bundle entry for a component that does not exist is a stale doc shipped to consumers — "
            + "delete the orphan overlay and regenerate: " + string.Join(", ", phantom.Take(20)));
    }

    /// <summary>
    /// Every <c>kind: "Component"</c> item inside each committed <c>tempo-blazor*.json</c> bundle at
    /// the repository root, keyed by file name and then by <c>itemName</c>. Assertions run per file —
    /// merging the bundles into one map would let an entry that is complete in one file launder the
    /// same entry being incomplete in another. The aggregate document nests items under
    /// <c>packages[].items</c>, so the search is recursive rather than top-level.
    /// </summary>
    private static IReadOnlyDictionary<string, Dictionary<string, DocEntry>> BundleDocs()
    {
        var root = ThemeCss.RepositoryRoot().FullName;
        var docs = new Dictionary<string, Dictionary<string, DocEntry>>(StringComparer.Ordinal);
        foreach (var file in Directory.GetFiles(root, "tempo-*.json", SearchOption.TopDirectoryOnly)
                     .OrderBy(f => f, StringComparer.Ordinal))
        {
            JsonElement document;
            try
            {
                using var parsed = JsonDocument.Parse(File.ReadAllText(file));
                document = parsed.RootElement.Clone();
            }
            catch (JsonException e)
            {
                throw new InvalidOperationException(
                    $"committed bundle is not valid JSON: {Path.GetFileName(file)}", e);
            }

            var fileDocs = new Dictionary<string, DocEntry>(StringComparer.Ordinal);
            CollectComponentItems(document, file, fileDocs);
            docs[Path.GetFileName(file)] = fileDocs;
        }

        return docs;
    }

    private static void CollectComponentItems(
        JsonElement element, string file, Dictionary<string, DocEntry> docs)
    {
        switch (element.ValueKind)
        {
            case JsonValueKind.Object:
                if (element.TryGetProperty("kind", out var kind)
                    && kind.ValueKind == JsonValueKind.String
                    && kind.GetString() == "Component"
                    && element.TryGetProperty("itemName", out var itemName)
                    && itemName.GetString() is { Length: > 0 } name)
                {
                    var parameters = new HashSet<string>(StringComparer.Ordinal);
                    if (element.TryGetProperty("parameters", out var array)
                        && array.ValueKind == JsonValueKind.Array)
                    {
                        foreach (var parameter in array.EnumerateArray())
                        {
                            if (parameter.TryGetProperty("name", out var pn)
                                && pn.GetString() is { Length: > 0 } p)
                            {
                                parameters.Add(p);
                            }
                        }
                    }

                    if (docs.TryGetValue(name, out var existing))
                    {
                        existing.Parameters.UnionWith(parameters);
                    }
                    else
                    {
                        docs[name] = new DocEntry(file, parameters);
                    }
                }
                else
                {
                    foreach (var property in element.EnumerateObject())
                    {
                        CollectComponentItems(property.Value, file, docs);
                    }
                }

                break;
            case JsonValueKind.Array:
                foreach (var item in element.EnumerateArray())
                {
                    CollectComponentItems(item, file, docs);
                }

                break;
        }
    }
}
