using System.Reflection;
using System.Text.Json;
using FluentAssertions;
using Microsoft.AspNetCore.Components;
using Tempo.Blazor.Tests.Theme;

namespace Tempo.Blazor.Tests.Documentation;

/// <summary>
/// Freshness guard for the component JSON documentation an MCP client and the package docs serve.
/// <para>
/// The documentation set under <c>JsonDocumentation/</c> is regenerated by
/// <c>JsonDocumentationGenerator</c>, but regeneration is a manual step — a parameter added to a
/// component since the last run simply does not exist for a consumer reading the docs, and a renamed
/// parameter leaves behind a phantom entry describing an API the component no longer has. Nothing
/// compared the two sides until this test.
/// </para>
/// <para>
/// The population is derived by reflection — the same view a consumer gets — over every
/// <c>Tempo.*.dll</c> the test project references: every non-abstract <c>IComponent</c> whose name
/// starts with <c>Tm</c> and which carries at least one <see cref="ParameterAttribute"/> property
/// (declared or inherited) must either have a <c>kind: "Component"</c> JSON entry or be named in
/// <see cref="UndocumentedComponents"/> — a frozen, itemized set that can only shrink by writing the
/// documentation, never grow by adding a component and staying silent.
/// </para>
/// <para>
/// Parameter sets are compared on both layers of the documentation model: overlay entries may not
/// name a parameter the component does not have (a stale name merges into the shipped bundle
/// verbatim), and the committed <c>tempo-blazor*.json</c> bundles must cover every settable
/// parameter while naming none that do not exist — so a source change without a regeneration, or a
/// stale overlay entry, both fail here.
/// </para>
/// </summary>
public class ComponentDocumentationFreshnessTests
{
    /// <summary>
    /// Components that ship <c>[Parameter]</c> surface but have no component JSON yet. The set is
    /// frozen: a component may leave it only by gaining documentation, and no component may enter
    /// it — a new component without documentation fails the population test below.
    /// </summary>
    private static readonly HashSet<string> UndocumentedComponents = new(StringComparer.Ordinal)
    {
        // __FROZEN_SET__
    };

    private static readonly HashSet<string> NonLibraryAssemblies = new(StringComparer.Ordinal)
    {
        "Tempo.Blazor.Tests",
        "Tempo.Blazor.Demo.Shared",
        "Tempo.Blazor.Demo.SharedUI",
    };

    /// <param name="Types">All component types sharing the item name — the library has exactly one
    /// such collision today (TmNotionEmojiPicker exists in a Shared/ and a UI/ variant); one doc
    /// entry must serve the union of their parameters.</param>
    private sealed record ComponentEntry(string Name, Type[] Types);

    private sealed record DocEntry(string File, HashSet<string> Parameters);

    private static string BaseName(string name)
    {
        var tick = name.IndexOf('`');
        return tick < 0 ? name : name[..tick];
    }

    private static bool IsParameter(PropertyInfo property)
        => property.GetCustomAttribute<ParameterAttribute>() is not null;

    /// <summary>Every public instance [Parameter] the component answers to, inherited included.</summary>
    private static string[] ReflectedParameters(Type type)
        => type.GetProperties(BindingFlags.Public | BindingFlags.Instance)
            .Where(IsParameter)
            .Select(p => p.Name)
            .Distinct(StringComparer.Ordinal)
            .OrderBy(n => n, StringComparer.Ordinal)
            .ToArray();

    private static string[] ReflectedParameters(ComponentEntry component)
        => component.Types.SelectMany(ReflectedParameters)
            .Distinct(StringComparer.Ordinal)
            .OrderBy(n => n, StringComparer.Ordinal)
            .ToArray();

    private static List<Assembly> LibraryAssemblies()
    {
        var assemblies = new List<Assembly>();
        foreach (var file in Directory.GetFiles(AppContext.BaseDirectory, "Tempo.*.dll"))
        {
            var name = Path.GetFileNameWithoutExtension(file);
            if (NonLibraryAssemblies.Contains(name))
            {
                continue;
            }

            try
            {
                assemblies.Add(Assembly.LoadFrom(file));
            }
            catch (Exception)
            {
                // A package dll that will not load in the test host carries no usable component
                // surface anyway — the manifest sweep, not this guard, owns reachability.
            }
        }

        return assemblies;
    }

    private static IEnumerable<Type> LoadableTypes(Assembly assembly)
    {
        try
        {
            return assembly.GetTypes();
        }
        catch (ReflectionTypeLoadException e)
        {
            return e.Types.Where(t => t is not null)!;
        }
    }

    /// <summary>
    /// The guard's denominator: non-abstract <c>Tm*</c> components with at least one
    /// <c>[Parameter]</c> anywhere on their public surface.
    /// </summary>
    private static List<ComponentEntry> ComponentPopulation()
        => LibraryAssemblies()
            .SelectMany(LoadableTypes)
            .Where(t => t is { IsAbstract: false }
                        && typeof(IComponent).IsAssignableFrom(t)
                        && BaseName(t.Name).StartsWith("Tm", StringComparison.Ordinal)
                        && ReflectedParameters(t).Length > 0)
            .GroupBy(t => BaseName(t.Name), StringComparer.Ordinal)
            .Select(g => new ComponentEntry(g.Key, g.OrderBy(t => t.FullName, StringComparer.Ordinal).ToArray()))
            .OrderBy(e => e.Name, StringComparer.Ordinal)
            .ToList();

    /// <summary>
    /// Every <c>kind: "Component"</c> item anywhere under <c>JsonDocumentation/</c> — both the
    /// flat <c>Components/</c> overlays and the per-package <c>Packages/&lt;id&gt;/items/</c> tree —
    /// keyed by <c>itemName</c>. A name documented twice merges its parameter sets: the guard cares
    /// that the parameter is documented somewhere, not about which overlay won the merge.
    /// </summary>
    private static Dictionary<string, DocEntry> ComponentDocs()
    {
        var root = Path.Combine(ThemeCss.RepositoryRoot().FullName, "JsonDocumentation");
        var docs = new Dictionary<string, DocEntry>(StringComparer.Ordinal);
        foreach (var file in Directory.GetFiles(root, "*.json", SearchOption.AllDirectories))
        {
            JsonElement document;
            try
            {
                using var parsed = JsonDocument.Parse(File.ReadAllText(file));
                document = parsed.RootElement.Clone();
            }
            catch (JsonException)
            {
                continue;
            }

            if (!document.TryGetProperty("kind", out var kind) || kind.GetString() != "Component"
                || !document.TryGetProperty("itemName", out var itemName))
            {
                continue;
            }

            var name = itemName.GetString();
            if (string.IsNullOrEmpty(name))
            {
                continue;
            }

            var parameters = new HashSet<string>(StringComparer.Ordinal);
            if (document.TryGetProperty("parameters", out var array) && array.ValueKind == JsonValueKind.Array)
            {
                foreach (var parameter in array.EnumerateArray())
                {
                    if (parameter.TryGetProperty("name", out var parameterName)
                        && parameterName.GetString() is { Length: > 0 } pn)
                    {
                        parameters.Add(pn);
                    }
                }
            }

            if (docs.TryGetValue(name, out var existing))
            {
                existing.Parameters.UnionWith(parameters);
            }
            else
            {
                docs[name] = new DocEntry(file, parameters);
            }
        }

        return docs;
    }

    /// <summary>
    /// Names of every documented TYPE, any kind — used to attribute inherited parameters to the
    /// base that documents them (e.g. <c>DataTestId</c> lives on <c>TmComponentBase</c>'s entry, not
    /// repeated in 162 derived components).
    /// </summary>
    private static HashSet<string> DocumentedTypeNames()
    {
        var root = Path.Combine(ThemeCss.RepositoryRoot().FullName, "JsonDocumentation");
        var names = new HashSet<string>(StringComparer.Ordinal);
        foreach (var file in Directory.GetFiles(root, "*.json", SearchOption.AllDirectories))
        {
            try
            {
                using var parsed = JsonDocument.Parse(File.ReadAllText(file));
                if (parsed.RootElement.TryGetProperty("itemName", out var itemName)
                    && itemName.GetString() is { Length: > 0 } name)
                {
                    names.Add(name);
                }
            }
            catch (JsonException)
            {
                // not a doc item
            }
        }

        return names;
    }

    /// <summary>
    /// Parameters the shipped documentation must name for this component: everything on its public
    /// surface EXCEPT <c>[Parameter(CaptureUnmatchedValues)]</c> splats — the generator's own
    /// convention never emits them — and names declared on an ancestor that has a documentation
    /// entry of its own (those are attributed to the base's page, as the merge pipeline does).
    /// </summary>
    private static string[] ExpectedParameters(ComponentEntry component, HashSet<string> documentedTypes)
        => component.Types.SelectMany(t => t.GetProperties(BindingFlags.Public | BindingFlags.Instance))
            .Where(IsParameter)
            .Where(p => p.GetCustomAttribute<ParameterAttribute>()!.CaptureUnmatchedValues is false)
            .Where(p => p.DeclaringType is null
                        || component.Types.Contains(p.DeclaringType)
                        || !documentedTypes.Contains(BaseName(p.DeclaringType.Name)))
            .Select(p => p.Name)
            .Distinct(StringComparer.Ordinal)
            .OrderBy(n => n, StringComparer.Ordinal)
            .ToArray();

    [Fact]
    public void Population_Is_Large_Enough_To_Be_The_Real_One()
    {
        // A reflection failure that silently yields a handful of types must fail loudly: the guard
        // is only as good as its denominator. ~290 Tm* components ship today; the floor is set far
        // below on purpose — it exists to catch "the scan saw nothing", not to ratchet growth.
        ComponentPopulation().Should().HaveCountGreaterThanOrEqualTo(150,
            "a denominator this small means the scan found no assemblies, not that the library shrank");
    }

    [Fact]
    public void Every_Component_With_Parameters_Is_Documented_Or_Frozen()
    {
        var docs = ComponentDocs();
        var undocumented = ComponentPopulation()
            .Where(c => !docs.ContainsKey(c.Name))
            .Select(c => c.Name)
            .ToHashSet(StringComparer.Ordinal);

        var unlisted = undocumented.Except(UndocumentedComponents).OrderBy(n => n).ToList();
        var stale = UndocumentedComponents.Except(undocumented).OrderBy(n => n).ToList();

        unlisted.Should().BeEmpty(
            "these components ship [Parameter] surface with no JsonDocumentation entry — document them; "
            + "the frozen set may only shrink, never grow: " + string.Join(", ", unlisted));
        stale.Should().BeEmpty(
            "these names are frozen as undocumented but are documented now — remove them from the set: "
            + string.Join(", ", stale));
    }

    [Fact]
    public void Documented_Parameters_Exist_On_The_Component()
    {
        var docs = ComponentDocs();

        var phantom = ComponentPopulation()
            .Where(c => docs.TryGetValue(c.Name, out _))
            .SelectMany(c =>
            {
                var real = ReflectedParameters(c).ToHashSet(StringComparer.Ordinal);
                return docs[c.Name].Parameters
                    .Where(name => !real.Contains(name))
                    .Select(name => $"{c.Name}.{name} ({Path.GetFileName(docs[c.Name].File)})");
            })
            .OrderBy(s => s, StringComparer.Ordinal)
            .ToList();

        phantom.Should().BeEmpty(
            "a documented parameter that no longer exists is a stale API promise, not documentation: "
            + string.Join(", ", phantom.Take(20)));
    }

    /// <summary>
    /// The shipped per-package bundles (<c>tempo-blazor*.json</c>) are what a consumer actually
    /// reads. For every component in the population the bundle entry must name every parameter
    /// declared on the component — a name absent there means the bundle is stale relative to the
    /// source (regenerate it) or the parameter is genuinely undocumented.
    /// <para>
    /// The expected set excludes <c>[Parameter(CaptureUnmatchedValues)]</c> properties (the
    /// generator's own convention skips the <c>@attributes</c> splat) and parameters declared on a
    /// documented ancestor — those live on the ancestor's entry, e.g. <c>TmComponentBase</c>'s
    /// <c>DataTestId</c>.
    /// </para>
    /// </summary>
    [Fact]
    public void Bundle_Covers_Every_Component_Parameter()
    {
        var bundles = BundleDocs();
        var documentedTypes = DocumentedTypeNames();

        var missing = ComponentPopulation()
            .SelectMany(c =>
            {
                var expected = ExpectedParameters(c, documentedTypes);
                if (!bundles.TryGetValue(c.Name, out var entry))
                {
                    return expected.Select(name => $"{c.Name}.{name} — component has no bundle entry at all");
                }

                return expected
                    .Where(name => !entry.Parameters.Contains(name))
                    .Select(name => $"{c.Name}.{name}");
            })
            .OrderBy(s => s, StringComparer.Ordinal)
            .ToList();

        missing.Should().BeEmpty(
            "parameters a consumer can set must appear in the shipped bundle — regenerate "
            + "tempo-blazor*.json after changing [Parameter] surface: " + string.Join(", ", missing.Take(20)));
    }

    [Fact]
    public void Bundle_Documents_No_Phantom_Parameters()
    {
        var bundles = BundleDocs();

        var phantom = ComponentPopulation()
            .Where(c => bundles.TryGetValue(c.Name, out _))
            .SelectMany(c =>
            {
                var real = ReflectedParameters(c).ToHashSet(StringComparer.Ordinal);
                return bundles[c.Name].Parameters
                    .Where(name => !real.Contains(name))
                    .Select(name => $"{c.Name}.{name}");
            })
            .OrderBy(s => s, StringComparer.Ordinal)
            .ToList();

        phantom.Should().BeEmpty(
            "the shipped bundle names a parameter the component does not have — stale overlay or stale "
            + "bundle: " + string.Join(", ", phantom.Take(20)));
    }

    /// <summary>
    /// Every <c>kind: "Component"</c> item inside the committed <c>tempo-blazor*.json</c> bundles at
    /// the repository root, keyed by <c>itemName</c>. The aggregate document nests items under
    /// <c>packages[].items</c>, so the search is recursive rather than top-level.
    /// </summary>
    private static Dictionary<string, DocEntry> BundleDocs()
    {
        var root = ThemeCss.RepositoryRoot().FullName;
        var docs = new Dictionary<string, DocEntry>(StringComparer.Ordinal);
        foreach (var file in Directory.GetFiles(root, "tempo-*.json", SearchOption.TopDirectoryOnly))
        {
            JsonElement document;
            try
            {
                using var parsed = JsonDocument.Parse(File.ReadAllText(file));
                document = parsed.RootElement.Clone();
            }
            catch (JsonException)
            {
                continue;
            }

            CollectComponentItems(document, file, docs);
        }

        return docs;
    }

    private static void CollectComponentItems(
        JsonElement element, string file, Dictionary<string, DocEntry> docs)
    {
        switch (element.ValueKind)
        {
            case JsonValueKind.Object:
                if (element.TryGetProperty("kind", out var kind)
                    && kind.ValueKind == JsonValueKind.String
                    && kind.GetString() == "Component"
                    && element.TryGetProperty("itemName", out var itemName)
                    && itemName.GetString() is { Length: > 0 } name)
                {
                    var parameters = new HashSet<string>(StringComparer.Ordinal);
                    if (element.TryGetProperty("parameters", out var array)
                        && array.ValueKind == JsonValueKind.Array)
                    {
                        foreach (var parameter in array.EnumerateArray())
                        {
                            if (parameter.TryGetProperty("name", out var pn)
                                && pn.GetString() is { Length: > 0 } p)
                            {
                                parameters.Add(p);
                            }
                        }
                    }

                    if (docs.TryGetValue(name, out var existing))
                    {
                        existing.Parameters.UnionWith(parameters);
                    }
                    else
                    {
                        docs[name] = new DocEntry(file, parameters);
                    }
                }
                else
                {
                    foreach (var property in element.EnumerateObject())
                    {
                        CollectComponentItems(property.Value, file, docs);
                    }
                }

                break;
            case JsonValueKind.Array:
                foreach (var item in element.EnumerateArray())
                {
                    CollectComponentItems(item, file, docs);
                }

                break;
        }
    }
}
